repos:
  # Go formatting (backend only)
  - repo: local
    hooks:
      - id: go-fmt-backend
        name: go-fmt-backend
        entry: sh -c 'cd backend && gofmt -w *.go pkg/**/*.go || true'
        language: system
        files: ^backend/.*\.go$
        pass_filenames: false
      - id: go-imports-backend
        name: go-imports-backend
        entry: sh -c 'cd backend && goimports -w *.go pkg/**/*.go || true'
        language: system
        files: ^backend/.*\.go$
        pass_filenames: false

  # JavaScript/TypeScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md)$
        exclude: ^(vendor/|node_modules/|dist/|build/)

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier-yaml
        files: \.(yaml|yml)$
        exclude: ^(vendor/|node_modules/)

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(k8s/.*\.yaml$|demo/.*\.yaml$) # Skip k8s and demo multi-doc files
      - id: check-json
      - id: check-merge-conflict
