apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero-manager
  namespace: velero-manager
  labels:
    app: velero-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-manager
  template:
    metadata:
      labels:
        app: velero-manager
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: velero-manager
      # DNS resolution for local homelab services
      hostAliases:
      - ip: "10.100.102.110"
        hostnames:
        - "keycloak.homelab.local"
      containers:
      - name: velero-manager
        image: localhost:32000/velero-manager:v2.3.3-fix6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: GIN_MODE
          value: "release"
        # ConfigMap references are not needed since we read directly from the ConfigMap
        # The application will read the ConfigMap and Secret directly using the K8s API
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: velero-manager
  namespace: velero-manager
  labels:
    app: velero-manager
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: velero-manager
