apiVersion: v1
kind: Secret
metadata:
  name: velero-manager-oidc-secret
  namespace: velero-manager
  labels:
    app: velero-manager
type: Opaque
stringData:
  # IMPORTANT: Replace with your actual client secret from your OIDC provider
  clientSecret: "your-oidc-client-secret-here"
