apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-manager-oidc-config
  namespace: velero-manager
  labels:
    app: velero-manager
data:
  # OIDC Configuration
  enabled: "false" # Set to "true" to enable OIDC authentication

  # Identity Provider Settings
  issuerURL: "" # e.g., https://keycloak.company.com/auth/realms/company
  clientID: "" # e.g., velero-manager
  redirectURL: "" # e.g., https://velero-manager.company.com/api/v1/auth/oidc/callback

  # Claim Mappings
  usernameClaim: "preferred_username"
  emailClaim: "email"
  fullNameClaim: "name"
  rolesClaim: "realm_access.roles"
  groupsClaim: "groups"

  # Role Mappings (JSON arrays)
  adminRoles: '["velero-admin", "admin"]'
  adminGroups: '["velero-administrators", "administrators"]'
  defaultRole: "user"
