apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    app.kubernetes.io/name: observability
    app.kubernetes.io/component: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: velero-manager
  labels:
    name: velero-manager
    app.kubernetes.io/name: velero-manager
    app.kubernetes.io/component: backup-management